<a href="https://colab.research.google.com/github/CodeCollectionRepository/NodeJSWebsite/blob/master/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.18127573, 0.2364617 , 0.8721524 , 0.07883024],
       [0.42681211, 0.58375154, 0.31829497, 0.54488335],
       [0.53646293, 0.70327019, 0.33971801, 0.8094578 ]])

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.7722,  0.0338, -0.0590, -0.3352],
        [ 0.0720, -0.4596,  0.7980, -0.9167],
        [-0.0869,  1.8005, -0.0435, -2.2409]])

In [6]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1813, 0.2365, 0.8722, 0.0788],
        [0.4268, 0.5838, 0.3183, 0.5449],
        [0.5365, 0.7033, 0.3397, 0.8095]], dtype=torch.float64)

Reshape and Slice

In [7]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch2 = torch.arange(10)

In [10]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
mytorch3 = torch.arange(10)
mytorch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
mytorch4 = mytorch3.view(2,5)
mytorch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
#shape and view will update
mytorch5 = torch.arange(10)
mytorch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
mytorch6 = mytorch5.reshape(2,5)
mytorch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
mytorch5[1] = 4141
mytorch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [17]:
mytorch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [18]:
#Slices
mytorch7 = torch.arange(10)
mytorch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
mytorch7[7]

tensor(7)

In [20]:
mytorch8 = mytorch7.reshape(5,2)
mytorch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
mytorch8[:,1]

tensor([1, 3, 5, 7, 9])

In [23]:
#return column
mytorch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])